name: anjali
description: "I love you Anjali, my love!"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  firebase_auth: ^4.16.0
  flutter_native_splash: ^2.3.9
  restart_app: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/